name: flowery_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  social_login_buttons: ^1.0.7

  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core_platform_interface: ^5.0.0

  google_sign_in: ^7.2.0

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/flowers/homeScreen/flowersCategories.png
    - assets/flowers/homeScreen/sweetsCategories.png
    - assets/flowers/homeScreen/plantsCategories.png
    - assets/flowers/homeScreen/bearCategories.png
    - assets/flowers/homeScreen/balloonsCategories.png
    - assets/flowers/homeScreen/AIFlorist.png
    - assets/flowers/homeScreen/bouquetCrafting.png
    - assets/flowers/homeScreen/Ranunculuses.jpg
    - assets/flowers/signInScreen/
    - assets/flowers/flowersCategory/
    - assets/flowers/products/
    - assets/flowers/logo.png