import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../main.dart';

// ─────────────────────────────────────────────────────────────
// ПЕРЕВОДЫ — вынесены в отдельные мапы для чистоты кода
// ─────────────────────────────────────────────────────────────

class LocalizationData {
  static const Map<String, Map<String, String>> data = {
    'en': _en,
    'ru': _ru,
    'kk': _kk,
  };

  static const Map<String, String> _en = {
    'home': 'Home',
    'search': 'Search',
    'favorites': 'Favorites',
    'cart': 'Cart',
    'profile': 'Profile',
    'myOrders': 'My Orders',
    'savedAddresses': 'Saved Addresses',
    'language': 'Language',
    'logout': 'Log out',
    'deleteAccount': 'Delete Account',
    'settings': 'Settings',
    'notifications': 'Notifications',
    'about_us': 'About Us',
    'app_name': 'Flowery',
    'about_app_description': 'Flowery is your personal assistant in the world of flowers. We use artificial intelligence to help you create the perfect bouquet for any occasion.',
    'our_mission_title': 'Our Mission',
    'our_mission_text': 'To make the process of choosing and buying flowers easy, creative, and accessible to everyone through modern technology.',
    'contact_info_title': 'Contacts',
    'cartEmpty': 'Your cart is empty',
    'browseFlowers': 'Browse flowers',
    'addSomeFlowers': 'Add some flowers to get started',
    'goToCheckout': 'Go to checkout',
    'total': 'Total',
    'delivery': 'Delivery',
    'price': 'Price',
    'clearCart': 'Clear cart?',
    'removeAllItems': 'Remove all items from your cart?',
    'commentSeller': 'Comment for the seller',
    'promocode': 'Promocode',
    'usePromocode': 'Use',
    'youHavePromocode': 'You have one promocode',
    'error_load_cart': 'Failed to load cart',
    'people_add_to_order': 'People add to the order',
    'postcard': 'Postcard',
    'clear': 'Clear',
    'cart_is_empty': 'Cart is empty',
    'orderDetails': 'Order details',
    'recipient': 'Recipient',
    'address': 'Address',
    'payment': 'Payment',
    'payOrder': 'Pay for the order',
    'myOrdersTitle': 'My Orders',
    'activeOrders': 'Active',
    'historyOrders': 'History',
    'noActiveOrders': 'No active orders',
    'repeatOrder': 'Repeat order',
    'orderComposition': 'Order composition',
    'courierComment': 'Comment for the courier',
    'addComment': 'Add',
    'savedAddressesTitle': 'Saved addresses',
    'addAddress': 'Add address',
    'noAddresses': 'No saved addresses yet',
    'defaultAddress': 'Default',
    'street': 'Street',
    'apartment': 'Apt./Office',
    'city': 'City',
    'deleteAddress': 'Delete address?',
    'signIn': 'Sign In',
    'signUp': 'Sign Up',
    'email': 'Email',
    'password': 'Password',
    'forgotPassword': 'Forgot password?',
    'noAccount': 'Don\'t have an account?',
    'haveAccount': 'Already have an account?',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'retry': 'Retry',
    'yes': 'Yes',
    'no': 'No',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'back': 'Back',
    'selectLanguage': 'Select Language',
    'notFound': 'Page not found',
    'goHome': 'Go to main',
    'error_load_shops': 'Failed to load shops',
    'no_shops_found': 'No shops found',
    'most_popular': 'Most popular',
    'search_hint_full': 'Flowers, markets, or gifts',
    'rating': 'rating',
    'review': 'review',
    'free_delivery': 'Free delivery',
    'bouquets': 'Bouquets',
    'markets': 'Markets',
    'no_favorite_bouquets': 'No favorite bouquets yet',
    'no_favorite_bouquets_hint': 'Tap the heart icon on any bouquet to save it',
    'no_favorite_markets': 'No favorite markets yet',
    'removed_from_favorites': 'removed from favorites',
    'error_load_favorites': 'Failed to load favorites',
    'error_load_addresses': 'Failed to load addresses',
    'address_selected': 'Address selected',
    'address_deleted': 'Address deleted',
    'error_delete_address': 'Failed to delete address',
    'delete_address_confirm': 'Are you sure you want to delete',
    'no_addresses_hint': 'Add your first address for faster checkout',
    'error_save_address': 'Failed to save',
    'flowers_and_bouquets': 'Flowers and bouquets',
    'sweets_and_gifts': 'Sweets and gifts',
    'included_flowers': 'Included flowers',
    'included_sweets': 'Included sweets',
    'includes': 'Includes',
    'excludes': 'Excludes',
    'apply_filters': 'Apply filters',
    'shops_nearby': 'shops nearby',
    'today': 'Today',
    'paid': 'Paid',
    'unknown': 'Unknown',
    'no_products_category': 'No products available for',
    'roses': 'Roses',
    'tulips': 'Tulips',
    'peonies': 'Peonies',
    'peony_roses': 'Peony roses',
    'chrysanthemums': 'Chrysanthemums',
    'alstroemerias': 'Alstroemerias',
    'amaryllis': 'Amaryllis',
    'anemones': 'Anemones',
    'asters': 'Asters',
    'cornflowers': 'Cornflowers',
    'carnations': 'Carnations',
    'chocolate': 'Chocolate',
    'macarons': 'Macarons',
    'cupcakes': 'Cupcakes',
    'cookies': 'Cookies',
    'candy': 'Candy',
    'marshmallows': 'Marshmallows',
    'caramel': 'Caramel',
    'nuts': 'Nuts',
    'berries': 'Berries',
    'honey': 'Honey',
    'cakes': 'Cakes',
    'gift_boxes': 'Gift boxes',
    'monobouquets': 'Monobouquets',
    'signature': 'Signature',
    'by_the_stem': 'By the stem',
    'in_a_box': 'In a box',
    'in_a_basket': 'In a basket',
    'bridal': 'Bridal',
    'in_a_wood_box': 'In a wood box',
    'reset_all': 'Reset all',
    'flowers_type': 'Flowers type',
    'sweets_type': 'Sweets type',
    'color': 'Color',
    'price_filter': 'Price',
    'delivery_time': 'Delivery time',
    'gift_box': 'Gift box',
    'product_not_found': 'Product not found',
    'shop_not_found': 'Shop not found',
    'added_to_favorites': 'Added to favorites',
    'removed_from_favorites_msg': 'Removed from favorites',
    'added_to_cart_msg': 'Added to cart',
    'failed_to_add_to_cart': 'Failed to add to cart',
    'verified_availability': 'Verified availability',
    'description': 'Description',
    'size': 'Size',
    'width': 'Width',
    'height': 'Height',
    'go_to_store': 'Go to store',
    'contact_shop': 'Contact shop',
    'buyer_protection': 'Buyer protection',
    'buyer_protection_desc': 'If the item doesn\'t match the description, you can return it at the shop\'s expense or receive a full refund.',
    'cancellation_policy': 'Cancellation policy',
    'cancellation_policy_desc': 'Free cancellation is available until delivery starts. You will receive a full refund.',
    'report_listing': 'Report this listing',
    'working_hours': 'Working hours',
    'about': 'About',
    'reviews_count': 'reviews',
    'items_count': 'items',
    'sales_count': 'sales',
    'free_delivery_in_hours': 'Free delivery in 2 hours',
    'admin_panel': 'Admin Panel',
    'user_management': 'User Management',
    'product_management': 'Product Management',
    'change_role': 'Change user role',
    'no_name': 'No name',
    'order_management': 'Order Management',
    'bouquet_requests': 'Bouquet Requests',
    'no_requests_yet': 'No requests yet 🌸',
    'request_status_pending': 'Pending',
    'request_status_accepted': 'Accepted',
    'request_status_completed': 'Completed',
    'request_status_cancelled': 'Cancelled',
    'accept': 'Accept',
    'complete': 'Complete',
    'contact_user': 'Contact user',
    'change_status': 'Change status',
    'ai_bouquet': 'AI Bouquet',
    'customize_bouquet': 'Customize your bouquet',
    'select_flowers_occasion_budget': 'Select flowers, occasion and budget',
    'describe_dream_bouquet': 'Describe your dream bouquet',
    'dream_bouquet_hint': 'e.g., Soft pink roses under 20k',
    'occasion': 'Occasion',
    'select_occasion': 'Select occasion',
    'colors': 'Colors',
    'budget': 'Budget',
    'from': 'From',
    'up_to': 'Up to',
    'flowers_to_include': 'Flowers to include',
    'flowers_to_avoid': 'Flowers to avoid',
    'include_external_results': 'Include results from Wolt/2GIS',
    'generate_bouquet_btn': 'Generate bouquet',
    'generating_bouquet': 'Generating your bouquet...',
    'your_bouquets': 'Your bouquets',
    'choose_and_send': 'Choose the one you like and send it to the florist',
    'regenerate_bouquets': 'Regenerate bouquets',
    'request_sent': 'Request sent!',
    'request_sent_desc': 'Our florist will contact you shortly to confirm the order for',
    'great': 'Great!',
    'send': 'Send',
    'view_3d': '3D View',
    'add': 'Add',
    'birthday': 'Birthday',
    'anniversary': 'Anniversary',
    'valentines_day': 'Valentine\'s Day',
    'march_8th': 'March 8th',
    'thank_you': 'Thank you',
    'congratulations': 'Congratulations',
    'pink': 'Pink',
    'red': 'Red',
    'white': 'White',
    'yellow': 'Yellow',
    'purple': 'Purple',
    'mixed': 'Mixed',
    'proposed_variations': 'Proposed Variations',
    'bouquet_composer': 'Bouquet Composer',
    'select_flowers': 'Select Flowers',
    'finalize_composition': 'Finalize Composition',
    'send_to_florist': 'Send to Florist',
    'paid_delivery': 'Paid delivery',
    'express_delivery': 'Express',
    'add_to_cart': 'Add to cart',
    'user_not_found': 'User not found',
    'wrong_password': 'Incorrect password',
    'invalid_credential': 'Incorrect email or password',
    'invalid_email': 'Please enter a valid email address',
    'user_disabled': 'This account has been disabled',
    'too_many_requests': 'Too many attempts. Try again later',
    'general_error': 'Something went wrong. Please try again.',
    'network_error': 'Network error. Check your connection.',
    'fill_all_fields': 'Please fill in all fields',
    'enter_valid_email': 'Please enter a valid email address',
    'passwords_dont_match': 'Passwords don\'t match',
    'min_6_chars': 'Minimum 6 characters',
    'confirm_password_hint': 'Re-enter your password',
    'welcome_to_flowery': 'Welcome to Flowery',
    'find_dream_flowers': 'Find your dream flowers!',
    'sign_up_apple': 'Sign Up with Apple',
    'sign_up_google': 'Sign Up with Google',
    'sign_up_email': 'Sign Up with Email',
    'or': 'or',
    'enter_email_hint': 'Enter your email',
    'enter_password_hint': 'Enter your password',
    'signing_in_btn': 'Signing in...',
    'registration_success_msg': 'Registration successful! 🎉',
    'email_already_in_use': 'This email is already registered',
    'operation_not_allowed': 'Registration is disabled',
    'enter_email_error': 'Enter email',
    'enter_password_error': 'Enter password',
    'confirm_password_error': 'Confirm password',
    'order_id_not_provided': 'Order ID not provided',
    'failed_to_load_order': 'Failed to load order',
    'order_repeated_success': 'Order repeated successfully! 🌸',
    'failed_to_repeat_order': 'Failed to repeat order',
    'order_not_found': 'Order not found',
    'order_number_label': 'Order',
    'faster_delivery': 'Faster',
    'delivery_time_subtitle': 'in 45 - 55 min.',
    'another_time': 'Another time',
    'choose_date_time': 'Choose date and time',
    'bank_card': 'Bank card',
    'pay_now': 'Pay now',
    'upon_receipt': 'Upon receipt',
    'payment_receipt': 'Payment receipt',
    'apt_office_floor_entrance': 'Apt./Office/Floor/Entrance',
    'apt_office_floor_entrance_hint': 'Apt. 510 /...',
    'important_details': 'Important details',
    'important_details_hint': 'For example: include your name in the SMS or arrange a surprise',
    'select_label': 'Select',
    'order_placed_title': 'Order placed!',
    'order_placed_msg': 'Your order has been placed successfully.',
    'failed_to_place_order': 'Failed to place order. Try again.',
    'order_status_placed': 'The order has been placed',
    'order_status_collecting': 'Collecting the order',
    'order_status_delivery': 'The courier is on his way',
    'order_status_delivered': 'The order has been delivered',
    'order_cancelled_msg': 'Order cancelled',
    'cancel_order_confirm_title': 'Cancel order?',
    'cancel_order_confirm_msg': 'Are you sure you want to cancel this order?',
    'support': 'Support',
    'call_support': 'Call support',
    'chat_with_us': 'Chat with us',
    'chat_courier': 'Chat with courier',
    'details': 'Details',
    'no_orders_yet': 'No orders yet 🌸',
    'order_preview': 'Order',
    'courier_comment_hint': 'Please write your wishes regarding the order composition, packaging and decoration.',
    'ready': 'Ready',
    'edit_address': 'Edit address',
    'add_new_address': 'Add new address',
    'street_address': 'Street address *',
    'street_required': 'Street is required',
    'street_hint': 'e.g., Uly Dala Avenue, 31',
    'apt_office_floor_label': 'Apartment / Office / Floor',
    'apt_office_floor_example': 'e.g., Apt. 510, 5th floor',
    'city_label': 'City *',
    'city_required': 'City is required',
    'city_hint': 'e.g., Astana',
    'set_as_default': 'Set as default address',
    'save_changes': 'Save changes',
    'error_load_profile': 'Failed to load profile',
    'error_sign_out': 'Failed to sign out. Please try again.',
    'flowers': 'Flowers',
    'sweets': 'Sweets',
    'plants': 'Plants',
    'bears': 'Bears',
    'balloons': 'Balloons',
    'ai_florist_title': 'AI Florist',
    'ai_florist_description': 'Choose flowers, set budget and occasion — AI will generate the perfect bouquet. Send it to a florist!',
    'generation': 'Generation',
    'to_florist': 'To Florist',
    'create_ai_bouquet': 'Create AI Bouquet',
    'top_pick': 'Top pick',
    'top_choice': 'Top Choice',
    'status_placed': 'Order placed',
    'status_collecting': 'Collecting order',
    'status_delivery': 'Courier is on the way',
    'status_in_progress': 'Order in progress',
    'delivery_today': 'We deliver flowers today',
    'searchHint': 'Search flowers, shops...',
    'searchResults': 'Search results',
    'noResults': 'Nothing found',
    'results_found': 'results found',
    'error_loading_product': 'Error loading product',
    'error_loading_shop': 'Error loading shop',
    'seed_complete': 'Seed complete!',
  };

  static const Map<String, String> _ru = {
    'home': 'Главная',
    'search': 'Поиск',
    'favorites': 'Избранное',
    'cart': 'Корзина',
    'profile': 'Профиль',
    'myOrders': 'Мои заказы',
    'savedAddresses': 'Адреса',
    'language': 'Язык',
    'logout': 'Выйти',
    'deleteAccount': 'Удалить аккаунт',
    'settings': 'Настройки',
    'notifications': 'Уведомления',
    'about_us': 'О нас',
    'app_name': 'Flowery',
    'about_app_description': 'Flowery — ваш личный помощник в мире цветов. Мы используем искусственный интеллект, чтобы помочь вам создать идеальный букет для любого повода.',
    'our_mission_title': 'Наша миссия',
    'our_mission_text': 'Сделать процесс выбора и покупки цветов простым, творческим и доступным каждому с помощью современных технологий.',
    'contact_info_title': 'Контакты',
    'cartEmpty': 'Корзина пуста',
    'browseFlowers': 'Посмотреть цветы',
    'addSomeFlowers': 'Добавьте цветы для начала',
    'goToCheckout': 'Оформить заказ',
    'total': 'Итого',
    'delivery': 'Доставка',
    'price': 'Цена',
    'clearCart': 'Очистить корзину?',
    'removeAllItems': 'Удалить все товары из корзины?',
    'commentSeller': 'Комментарий продавцу',
    'promocode': 'Промокод',
    'usePromocode': 'Применить',
    'youHavePromocode': 'У вас есть промокод',
    'error_load_cart': 'Не удалось загрузить корзину',
    'people_add_to_order': 'Добавьте к заказу',
    'postcard': 'Открытка',
    'clear': 'Очистить',
    'cart_is_empty': 'Корзина пуста',
    'orderDetails': 'Детали заказа',
    'recipient': 'Получатель',
    'address': 'Адрес',
    'payment': 'Оплата',
    'payOrder': 'Оплатить заказ',
    'myOrdersTitle': 'Мои заказы',
    'activeOrders': 'Активные',
    'historyOrders': 'История',
    'noActiveOrders': 'Нет активных заказов',
    'repeatOrder': 'Повторить заказ',
    'orderComposition': 'Состав заказа',
    'courierComment': 'Комментарий курьеру',
    'addComment': 'Добавить',
    'savedAddressesTitle': 'Сохранённые адреса',
    'addAddress': 'Добавить адрес',
    'noAddresses': 'Нет сохранённых адресов',
    'defaultAddress': 'По умолчанию',
    'street': 'Улица',
    'apartment': 'Кв./Офис',
    'city': 'Город',
    'deleteAddress': 'Удалить адрес?',
    'signIn': 'Войти',
    'signUp': 'Регистрация',
    'email': 'Email',
    'password': 'Пароль',
    'forgotPassword': 'Забыли пароль?',
    'noAccount': 'Нет аккаунта?',
    'haveAccount': 'Уже есть аккаунт?',
    'save': 'Сохранить',
    'cancel': 'Отмена',
    'delete': 'Удалить',
    'edit': 'Редактировать',
    'retry': 'Повторить',
    'yes': 'Да',
    'no': 'Нет',
    'loading': 'Загрузка...',
    'error': 'Ошибка',
    'success': 'Успешно',
    'back': 'Назад',
    'selectLanguage': 'Выберите язык',
    'notFound': 'Страница не найдена',
    'goHome': 'На главную',
    'error_load_shops': 'Не удалось загрузить магазины',
    'no_shops_found': 'Магазины не найдены',
    'most_popular': 'Самые популярные',
    'search_hint_full': 'Цветы, магазины или подарки',
    'rating': 'рейтинг',
    'review': 'отзыв',
    'free_delivery': 'Бесплатная доставка',
    'bouquets': 'Букеты',
    'markets': 'Магазины',
    'no_favorite_bouquets': 'Нет избранных букетов',
    'no_favorite_bouquets_hint': 'Нажмите на сердечко на букете, чтобы сохранить его',
    'no_favorite_markets': 'Нет избранных магазинов',
    'removed_from_favorites': 'удалено из избранного',
    'error_load_favorites': 'Не удалось загрузить избранное',
    'error_load_addresses': 'Не удалось загрузить адреса',
    'address_selected': 'Адрес выбран',
    'address_deleted': 'Адрес удален',
    'error_delete_address': 'Не удалось удалить адрес',
    'delete_address_confirm': 'Вы уверены, что хотите удалить',
    'no_addresses_hint': 'Добавьте адрес для быстрого оформления',
    'error_save_address': 'Ошибка сохранения',
    'flowers_and_bouquets': 'Цветы и букеты',
    'sweets_and_gifts': 'Сладости и подарки',
    'included_flowers': 'Цветы в составе',
    'included_sweets': 'Сладости в составе',
    'includes': 'Включает',
    'excludes': 'Исключает',
    'apply_filters': 'Применить фильтры',
    'shops_nearby': 'магазинов рядом',
    'today': 'Сегодня',
    'paid': 'Платно',
    'unknown': 'Неизвестно',
    'no_products_category': 'Нет товаров в категории',
    'roses': 'Розы',
    'tulips': 'Тюльпаны',
    'peonies': 'Пионы',
    'peony_roses': 'Пионовидные розы',
    'chrysanthemums': 'Хризантемы',
    'alstroemerias': 'Альстромерии',
    'amaryllis': 'Амариллисы',
    'anemones': 'Анемоны',
    'asters': 'Астры',
    'cornflowers': 'Васильки',
    'carnations': 'Гвоздики',
    'chocolate': 'Шоколад',
    'macarons': 'Макаруны',
    'cupcakes': 'Капкейки',
    'cookies': 'Печенье',
    'candy': 'Конфеты',
    'marshmallows': 'Зефир',
    'caramel': 'Карамель',
    'nuts': 'Орехи',
    'berries': 'Ягоды',
    'honey': 'Мед',
    'cakes': 'Торты',
    'gift_boxes': 'Подарочные наборы',
    'monobouquets': 'Монобукеты',
    'signature': 'Авторские',
    'by_the_stem': 'Поштучно',
    'in_a_box': 'В коробке',
    'in_a_basket': 'В корзине',
    'bridal': 'Свадебные',
    'in_a_wood_box': 'В деревянном ящике',
    'reset_all': 'Сбросить всё',
    'flowers_type': 'Тип цветов',
    'sweets_type': 'Тип сладостей',
    'color': 'Цвет',
    'price_filter': 'Цена',
    'delivery_time': 'Время доставки',
    'gift_box': 'Подарочная упаковка',
    'product_not_found': 'Товар не найден',
    'shop_not_found': 'Магазин не найден',
    'added_to_favorites': 'Добавлено в избранное',
    'removed_from_favorites_msg': 'Удалено из избранного',
    'added_to_cart_msg': 'Добавлено в корзину',
    'failed_to_add_to_cart': 'Не удалось добавить в корзину',
    'verified_availability': 'Наличие подтверждено',
    'description': 'Описание',
    'size': 'Размер',
    'width': 'Ширина',
    'height': 'Высота',
    'go_to_store': 'В магазин',
    'contact_shop': 'Связаться с магазином',
    'buyer_protection': 'Защита покупателя',
    'buyer_protection_desc': 'Если товар не соответствует описанию, вы можете вернуть его за счет магазина или получить полный возврат средств.',
    'cancellation_policy': 'Правила отмены',
    'cancellation_policy_desc': 'Бесплатная отмена возможна до начала доставки. Вы получите полный возврат средств.',
    'report_listing': 'Пожаловаться на товар',
    'working_hours': 'Часы работы',
    'about': 'О магазине',
    'reviews_count': 'отзывов',
    'items_count': 'товаров',
    'sales_count': 'продаж',
    'free_delivery_in_hours': 'Бесплатная доставка за 2 часа',
    'admin_panel': 'Панель администратора',
    'user_management': 'Управление пользователями',
    'product_management': 'Управление товарами',
    'change_role': 'Изменить роль пользователя',
    'no_name': 'Без имени',
    'order_management': 'Управление заказами',
    'bouquet_requests': 'Запросы на букеты',
    'no_requests_yet': 'Запросов пока нет 🌸',
    'request_status_pending': 'В ожидании',
    'request_status_accepted': 'Принят',
    'request_status_completed': 'Завершен',
    'request_status_cancelled': 'Отменен',
    'accept': 'Принять',
    'complete': 'Завершить',
    'contact_user': 'Связаться',
    'change_status': 'Сменить статус',
    'ai_bouquet': 'AI Букет',
    'customize_bouquet': 'Настройте ваш букет',
    'select_flowers_occasion_budget': 'Выберите цветы, повод и бюджет',
    'describe_dream_bouquet': 'Опишите ваш идеальный букет',
    'dream_bouquet_hint': 'напр. Нежные розовые розы до 20к',
    'occasion': 'Повод',
    'select_occasion': 'Выберите повод',
    'colors': 'Цвета',
    'budget': 'Бюджет',
    'from': 'От',
    'up_to': 'До',
    'flowers_to_include': 'Включить цветы',
    'flowers_to_avoid': 'Избегать цветов',
    'include_external_results': 'Включить результаты из Wolt/2GIS',
    'generate_bouquet_btn': 'Сгенерировать букет',
    'generating_bouquet': 'Генерация вашего букета...',
    'your_bouquets': 'Ваши букеты',
    'choose_and_send': 'Выберите понравившийся и отправьте флористу',
    'regenerate_bouquets': 'Перегенерировать букеты',
    'request_sent': 'Запрос отправлен!',
    'request_sent_desc': 'Наш флорист свяжется с вами в ближайшее время для подтверждения заказа',
    'great': 'Отлично!',
    'send': 'Отправить',
    'view_3d': '3D Вид',
    'add': 'Добавить',
    'birthday': 'День рождения',
    'anniversary': 'Годовщина',
    'valentines_day': 'День Св. Валентина',
    'march_8th': '8 Марта',
    'thank_you': 'Спасибо',
    'congratulations': 'Поздравляю',
    'pink': 'Розовый',
    'red': 'Красный',
    'white': 'Белый',
    'yellow': 'Желтый',
    'purple': 'Фиолетовый',
    'mixed': 'Микс',
    'proposed_variations': 'Предложенные варианты',
    'bouquet_composer': 'Конструктор букета',
    'select_flowers': 'Выберите цветы',
    'finalize_composition': 'Завершить составление',
    'send_to_florist': 'Отправить флористу',
    'paid_delivery': 'Платная доставка',
    'express_delivery': 'Экспресс',
    'add_to_cart': 'В корзину',
    'user_not_found': 'Пользователь не найден',
    'wrong_password': 'Неверный пароль',
    'invalid_credential': 'Неверный email или пароль',
    'invalid_email': 'Введите корректный email',
    'user_disabled': 'Аккаунт отключен',
    'too_many_requests': 'Слишком много попыток. Попробуйте позже',
    'general_error': 'Что-то пошло не так. Попробуйте еще раз.',
    'network_error': 'Ошибка сети. Проверьте подключение.',
    'fill_all_fields': 'Пожалуйста, заполните все поля',
    'enter_valid_email': 'Введите корректный email адрес',
    'passwords_dont_match': 'Пароли не совпадают',
    'min_6_chars': 'Минимум 6 символов',
    'confirm_password_hint': 'Повторите пароль',
    'welcome_to_flowery': 'Добро пожаловать в Flowery',
    'find_dream_flowers': 'Найдите цветы своей мечты!',
    'sign_up_apple': 'Войти через Apple',
    'sign_up_google': 'Войти через Google',
    'sign_up_email': 'Регистрация по почте',
    'or': 'или',
    'enter_email_hint': 'Введите email',
    'enter_password_hint': 'Введите пароль',
    'signing_in_btn': 'Вход...',
    'registration_success_msg': 'Регистрация успешна! 🎉',
    'email_already_in_use': 'Этот email уже зарегистрирован',
    'operation_not_allowed': 'Регистрация отключена',
    'enter_email_error': 'Введите email',
    'enter_password_error': 'Введите пароль',
    'confirm_password_error': 'Подтвердите пароль',
    'order_id_not_provided': 'ID заказа не указан',
    'failed_to_load_order': 'Не удалось загрузить заказ',
    'order_repeated_success': 'Заказ успешно повторен! 🌸',
    'failed_to_repeat_order': 'Не удалось повторить заказ',
    'order_not_found': 'Заказ не найден',
    'order_number_label': 'Заказ',
    'faster_delivery': 'Поближе',
    'delivery_time_subtitle': 'через 45 - 55 мин.',
    'another_time': 'В другое время',
    'choose_date_time': 'Выбрать дату и время',
    'bank_card': 'Банковская карта',
    'pay_now': 'Оплатить сейчас',
    'upon_receipt': 'При получении',
    'payment_receipt': 'Оплата при доставке',
    'apt_office_floor_entrance': 'Кв./Офис/Этаж/Подъезд',
    'apt_office_floor_entrance_hint': 'Кв. 510 /...',
    'important_details': 'Важные детали',
    'important_details_hint': 'Например: напишите ваше имя в SMS или устройте сюрприз',
    'select_label': 'Выбрать',
    'order_placed_title': 'Заказ оформлен!',
    'order_placed_msg': 'Ваш заказ успешно размещен.',
    'failed_to_place_order': 'Ошибка оформления заказа.',
    'order_status_placed': 'Заказ оформлен',
    'order_status_collecting': 'Сборка заказа',
    'order_status_delivery': 'Курьер в пути',
    'order_status_delivered': 'Заказ доставлен',
    'order_status_cancelled': 'Заказ отменен',
    'cancel_order_confirm_title': 'Отменить заказ?',
    'cancel_order_confirm_msg': 'Вы уверены, что хотите отменить этот заказ?',
    'support': 'Поддержка',
    'call_support': 'Позвонить',
    'chat_with_us': 'Написать в чат',
    'details': 'Детали',
    'no_orders_yet': 'Заказов пока нет 🌸',
    'order_preview': 'Заказ',
    'courier_comment_hint': 'Напишите ваши пожелания по составу, упаковке и оформлению заказа.',
    'ready': 'Готово',
    'edit_address': 'Редактировать адрес',
    'add_new_address': 'Добавить новый адрес',
    'street_address': 'Улица и дом *',
    'street_required': 'Введите улицу',
    'street_hint': 'напр. пр. Республики, 12',
    'apt_office_floor_label': 'Квартира / Офис / Этаж',
    'apt_office_floor_example': 'напр. Кв. 510, 5 этаж',
    'city_label': 'Город *',
    'city_required': 'Введите город',
    'city_hint': 'напр. Астана',
    'set_as_default': 'Сделать основным адресом',
    'save_changes': 'Сохранить изменения',
    'error_load_profile': 'Не удалось загрузить профиль',
    'error_sign_out': 'Ошибка выхода. Попробуйте еще раз.',
    'flowers': 'Цветы',
    'sweets': 'Тәттілер',
    'plants': 'Растения',
    'bears': 'Медведи',
    'balloons': 'Шары',
    'ai_florist_title': 'AI Флорист',
    'ai_florist_description': 'Выберите цветы, укажите бюджет и повод — AI создаст идеальный букет. Отправьте его флористу!',
    'generation': 'Генерация',
    'to_florist': 'Флористу',
    'create_ai_bouquet': 'Создать букет с AI',
    'top_pick': 'Лучший выбор',
    'top_choice': 'Топ выбор',
    'status_placed': 'Заказ оформлен',
    'status_collecting': 'Сборка заказа',
    'status_delivery': 'Курьер в пути',
    'status_in_progress': 'Заказ выполняется',
    'delivery_today': 'Доставим цветы сегодня',
    'searchHint': 'Поиск цветов, магазинов...',
    'searchResults': 'Результаты поиска',
    'noResults': 'Ничего не найдено',
    'results_found': 'результатов найдено',
    'error_loading_product': 'Ошибка загрузки товара',
    'error_loading_shop': 'Ошибка загрузки магазина',
    'seed_complete': 'Сидирование завершено!',
  };

  static const Map<String, String> _kk = {
    'home': 'Басты',
    'search': 'Іздеу',
    'favorites': 'Таңдаулы',
    'cart': 'Себет',
    'profile': 'Профиль',
    'myOrders': 'Менің тапсырыстарым',
    'savedAddresses': 'Мекенжайлар',
    'language': 'Тіл',
    'logout': 'Шығу',
    'deleteAccount': 'Аккаунтты жою',
    'settings': 'Параметрлер',
    'notifications': 'Хабарламалар',
    'about_us': 'Біз туралы',
    'app_name': 'Flowery',
    'about_app_description': 'Flowery — гүлдер әлеміндегі сіздің жеке көмекшіңіз. Біз кез келген жағдайға мінсіз букет жасауға көмектесу үшін жасанды интеллектті қолданамыз.',
    'our_mission_title': 'Біздің миссиямыз',
    'our_mission_text': 'Заманауи технологиялар арқылы гүлдерді таңдау және сатып алу процесін әркімге оңай, шығармашылық және қолжетімді ету.',
    'contact_info_title': 'Байланыстар',
    'cartEmpty': 'Себет бос',
    'browseFlowers': 'Гүлдерді қарау',
    'addSomeFlowers': 'Бастау үшін гүл қосыңыз',
    'goToCheckout': 'Тапсырысты рәсімдеу',
    'total': 'Барлығы',
    'delivery': 'Жеткізу',
    'price': 'Баға',
    'clearCart': 'Себетті тазалау?',
    'removeAllItems': 'Барлық тауарларды себеттен жою?',
    'commentSeller': 'Сатушыға пікір',
    'promocode': 'Промокод',
    'usePromocode': 'Қолдану',
    'youHavePromocode': 'Сізде промокод бар',
    'error_load_cart': 'Себетті жүктеу мүмкін болмады',
    'people_add_to_order': 'Тапсырысқа қосыңыз',
    'postcard': 'Ашық хат',
    'clear': 'Тазалау',
    'cart_is_empty': 'Себет бос',
    'orderDetails': 'Тапсырыс мәліметтері',
    'recipient': 'Алушы',
    'address': 'Мекенжай',
    'payment': 'Төлем',
    'payOrder': 'Тапсырысты төлеу',
    'myOrdersTitle': 'Тапсырыстарым',
    'activeOrders': 'Белсенді',
    'historyOrders': 'Тарих',
    'noActiveOrders': 'Белсенді тапсырыс жоқ',
    'repeatOrder': 'Тапсырысты қайталау',
    'orderComposition': 'Тапсырыс құрамы',
    'courierComment': 'Курьерге пікір',
    'addComment': 'Қосу',
    'savedAddressesTitle': 'Сақталған мекенжайлар',
    'addAddress': 'Мекенжай қосу',
    'noAddresses': 'Сақталған мекенжай жоқ',
    'defaultAddress': 'Әдепкі',
    'street': 'Көше',
    'apartment': 'Пәтер/Кеңсе',
    'city': 'Қала',
    'deleteAddress': 'Мекенжайды жою?',
    'signIn': 'Кіру',
    'signUp': 'Тіркелу',
    'email': 'Email',
    'password': 'Құпия сөз',
    'forgotPassword': 'Құпия сөзді ұмыттыңыз ба?',
    'noAccount': 'Аккаунт жоқ па?',
    'haveAccount': 'Аккаунт бар ма?',
    'save': 'Сақтау',
    'cancel': 'Болдырмау',
    'delete': 'Жою',
    'edit': 'Өңдеу',
    'retry': 'Қайталау',
    'yes': 'Иә',
    'no': 'Жоқ',
    'loading': 'Жүктелуде...',
    'error': 'Қате',
    'success': 'Сәтті',
    'back': 'Артқа',
    'selectLanguage': 'Тілді таңдаңыз',
    'notFound': 'Бет табылмады',
    'goHome': 'Басты бетке',
    'error_load_shops': 'Дүкендерді жүктеу қатесі',
    'no_shops_found': 'Дүкендер табылмады',
    'most_popular': 'Ең танымал',
    'search_hint_full': 'Гүлдер, дүкендер немесе сыйлықтар',
    'rating': 'рейтинг',
    'review': 'пікір',
    'free_delivery': 'Тегін жеткізу',
    'bouquets': 'Букеттер',
    'markets': 'Дүкендер',
    'no_favorite_bouquets': 'Таңдаулы букеттер жоқ',
    'no_favorite_bouquets_hint': 'Сақтау үшін букеттегі жүрекшені басыңыз',
    'no_favorite_markets': 'Таңдаулы дүкендер жоқ',
    'removed_from_favorites': 'таңдаулыдан жойылды',
    'error_load_favorites': 'Таңдаулыны жүктеу қатесі',
    'error_load_addresses': 'Мекенжайларды жүктеу қатесі',
    'address_selected': 'Мекенжай таңдалды',
    'address_deleted': 'Мекенжай жойылды',
    'error_delete_address': 'Мекенжайды жою қатесі',
    'delete_address_confirm': 'Жоюды растайсыз ба',
    'no_addresses_hint': 'Жылдам ресімдеу үшін мекенжай қосыңыз',
    'error_save_address': 'Сақтау қатесі',
    'flowers_and_bouquets': 'Гүлдер мен букеттер',
    'sweets_and_gifts': 'Тәттілер мен сыйлықтар',
    'included_flowers': 'Құрамындағы гүлдер',
    'included_sweets': 'Құрамындағы тәттілер',
    'includes': 'Құрамында бар',
    'excludes': 'Құрамында жоқ',
    'apply_filters': 'Сүзгілерді қолдану',
    'shops_nearby': 'жақын маңдағы дүкендер',
    'today': 'Бүгін',
    'paid': 'Ақылы',
    'unknown': 'Белгісіз',
    'no_products_category': 'Санатта тауарлар жоқ',
    'roses': 'Розалар',
    'tulips': 'Қызғалдақтар',
    'peonies': 'Пиондар',
    'peony_roses': 'Пион тәрізді розалар',
    'chrysanthemums': 'Хризантемалар',
    'alstroemerias': 'Альстромериялар',
    'amaryllis': 'Амариллистер',
    'anemones': 'Анемондар',
    'asters': 'Астралар',
    'cornflowers': 'Көкгүлдер',
    'carnations': 'Қалампырлар',
    'chocolate': 'Шоколад',
    'macarons': 'Макарундар',
    'cupcakes': 'Капкейктер',
    'cookies': 'Печеньелер',
    'candy': 'Кәмпиттер',
    'marshmallows': 'Зефир',
    'caramel': 'Карамель',
    'nuts': 'Жаңғақтар',
    'berries': 'Жидектер',
    'honey': 'Бал',
    'cakes': 'Торттар',
    'gift_boxes': 'Сыйлық жиынтықтары',
    'monobouquets': 'Монобукеттер',
    'signature': 'Авторлық',
    'by_the_stem': 'Дана бойынша',
    'in_a_box': 'Қорапта',
    'in_a_basket': 'Себетте',
    'bridal': 'Үйлену тойына',
    'in_a_wood_box': 'Ағаш жәшікте',
    'reset_all': 'Барлығын қайтару',
    'flowers_type': 'Гүл түрі',
    'sweets_type': 'Тәтті түрі',
    'color': 'Түсі',
    'price_filter': 'Бағасы',
    'delivery_time': 'Жеткізу уақыты',
    'gift_box': 'Сыйлық қаптамасы',
    'product_not_found': 'Өнім табылмады',
    'shop_not_found': 'Дүкен табылмады',
    'added_to_favorites': 'Таңдаулыға қосылды',
    'removed_from_favorites_msg': 'Таңдаулыдан жойылды',
    'added_to_cart_msg': 'Себетке қосылды',
    'failed_to_add_to_cart': 'Себетке қосу қатесі',
    'verified_availability': 'Расталған қолжетімділік',
    'description': 'Сипаттамасы',
    'size': 'Өлшемі',
    'width': 'Ені',
    'height': 'Биіктігі',
    'go_to_store': 'Дүкенге бару',
    'contact_shop': 'Дүкенмен байланысу',
    'buyer_protection': 'Сатып алушыны қорғау',
    'buyer_protection_desc': 'Егер тауар сипаттамаға сәйкес келмесе, сіз оны дүкен есебінен қайтара аласыз немесе ақшаңызды толық қайтара аласыз.',
    'cancellation_policy': 'Болдырмау ережелері',
    'cancellation_policy_desc': 'Жеткізу басталғанға дейін тегін бас тартуға болады. Ақшаңыз толық қайтарылады.',
    'report_listing': 'Тауарға шағымдану',
    'working_hours': 'Жұмыс уақыты',
    'about': 'Дүкен туралы',
    'reviews_count': 'пікірлер',
    'items_count': 'тауарлар',
    'sales_count': 'сатылымдар',
    'free_delivery_in_hours': '2 сағатта тегін жеткізу',
    'admin_panel': 'Әкімші панелі',
    'user_management': 'Пайдаланушыларды басқару',
    'product_management': 'Тауарларды басқару',
    'change_role': 'Пайдаланушы рөлін өзгерту',
    'no_name': 'Аты жоқ',
    'order_management': 'Тапсырыстарды басқару',
    'bouquet_requests': 'Букеттерге сұраныстар',
    'no_requests_yet': 'Сұраныстар жоқ 🌸',
    'request_status_pending': 'Күтілуде',
    'request_status_accepted': 'Қабылданды',
    'request_status_completed': 'Аяқталды',
    'request_status_cancelled': 'Тоқтатылды',
    'accept': 'Қабылдау',
    'complete': 'Аяқтау',
    'contact_user': 'Байланысу',
    'change_status': 'Мәртебені өзгерту',
    'ai_bouquet': 'AI Букет',
    'customize_bouquet': 'Букетіңізді реттеңіз',
    'select_flowers_occasion_budget': 'Гүлдерді, поводты және бюджетті таңдаңыз',
    'describe_dream_bouquet': 'Өзіңіздің мінсіз букетіңізді сипаттаңыз',
    'dream_bouquet_hint': 'мыс. 20 мыңға дейінгі нәзік қызғылт розалар',
    'occasion': 'Повод',
    'select_occasion': 'Поводты таңдаңыз',
    'colors': 'Түстер',
    'budget': 'Бюджет',
    'from': 'Бастап',
    'up_to': 'Дейін',
    'flowers_to_include': 'Гүлдерді қосу',
    'flowers_to_avoid': 'Гүлдерден аулақ болу',
    'include_external_results': 'Wolt/2GIS нәтижелерін қосу',
    'generate_bouquet_btn': 'Букетті жасау',
    'generating_bouquet': 'Букетіңіз жасалуда...',
    'your_bouquets': 'Сіздің букеттеріңіз',
    'choose_and_send': 'Өзіңізге ұнағанын таңдап, флористке жіберіңіз',
    'regenerate_bouquets': 'Букеттерді қайта жасау',
    'request_sent': 'Сұраныс жіберілді!',
    'request_sent_desc': 'Біздің флорист тапсырысты растау үшін жақын арада сізбен байланысады',
    'great': 'Тамаша!',
    'send': 'Жіберу',
    'view_3d': '3D Көрініс',
    'add': 'Қосу',
    'birthday': 'Туған күн',
    'anniversary': 'Мерейтой',
    'valentines_day': 'Ғашықтар күні',
    'march_8th': '8 Наурыз',
    'thank_you': 'Рақмет',
    'congratulations': 'Құттықтаймын',
    'pink': 'Қызғылт',
    'red': 'Қызыл',
    'white': 'Ақ',
    'yellow': 'Сары',
    'purple': 'Күлгін',
    'mixed': 'Микс',
    'proposed_variations': 'Ұсынылған нұсқалар',
    'bouquet_composer': 'Букет конструкторы',
    'select_flowers': 'Гүлдерді таңдаңыз',
    'finalize_composition': 'Құрастыруды аяқтау',
    'send_to_florist': 'Флористке жіберу',
    'paid_delivery': 'Ақылы жеткізу',
    'express_delivery': 'Экспресс',
    'add_to_cart': 'Себетке',
    'user_not_found': 'Пайдаланушы табылмады',
    'wrong_password': 'Құпия сөз қате',
    'invalid_credential': 'Email немесе құпия сөз қате',
    'invalid_email': 'Email-ды дұрыс енгізіңіз',
    'user_disabled': 'Аккаунт бұғатталған',
    'too_many_requests': 'Әрекет тым көп. Кейінірек көріңіз',
    'general_error': 'Бірдеңе қате кетті. Қайталап көріңіз.',
    'network_error': 'Желі қатесі. Қосылымды тексеріңіз.',
    'fill_all_fields': 'Барлық өрістерді толтырыңыз',
    'enter_valid_email': 'Email-ды дұрыс енгізіңіз',
    'passwords_dont_match': 'Құпия сөздер сәйкес келмейді',
    'min_6_chars': 'Кемінде 6 таңба',
    'confirm_password_hint': 'Құпия сөзді қайталаңыз',
    'welcome_to_flowery': 'Flowery-ге қош келдіңіз',
    'find_dream_flowers': 'Арман гүлдеріңізді табыңыз!',
    'sign_up_apple': 'Apple арқылы кіру',
    'sign_up_google': 'Google арқылы кіру',
    'sign_up_email': 'Email арқылы тіркелу',
    'or': 'немесе',
    'enter_email_hint': 'Email-ды енгізіңіз',
    'enter_password_hint': 'Құпия сөзді енгізіңіз',
    'signing_in_btn': 'Кіру...',
    'registration_success_msg': 'Тіркелу сәтті аяқталды! 🎉',
    'email_already_in_use': 'Бұл email тіркелген',
    'operation_not_allowed': 'Тіркелу мүмкін емес',
    'enter_email_error': 'Email енгізіңіз',
    'enter_password_error': 'Құпия сөзді енгізіңіз',
    'confirm_password_error': 'Құпия сөзді растаңыз',
    'order_id_not_provided': 'Тапсырыс ID көрсетілмеген',
    'failed_to_load_order': 'Тапсырысты жүктеу мүмкін болмады',
    'order_repeated_success': 'Тапсырыс сәтті қайталанды! 🌸',
    'failed_to_repeat_order': 'Тапсырысты қайталау қатесі',
    'order_not_found': 'Тапсырыс табылмады',
    'order_number_label': 'Тапсырыс',
    'faster_delivery': 'Жақынырақ',
    'delivery_time_subtitle': '45 - 55 мин ішінде',
    'another_time': 'Басқа уақыт',
    'choose_date_time': 'Күнді және уақытты таңдау',
    'bank_card': 'Банк картасы',
    'pay_now': 'Қазір төлеу',
    'upon_receipt': 'Алған кезде',
    'payment_receipt': 'Жеткізу кезінде төлеу',
    'apt_office_floor_entrance': 'Пәтер/Кеңсе/Қабат/Кіреберіс',
    'apt_office_floor_entrance_hint': 'Пәтер 510 /...',
    'important_details': 'Маңызды мәліметтер',
    'important_details_hint': 'Мысалы: SMS-ке атыңызды жазыңыз немесе тосын сый жасаңыз',
    'select_label': 'Таңдау',
    'order_placed_title': 'Тапсырыс ресімделді!',
    'order_placed_msg': 'Тапсырысыңыз сәтті қабылданды.',
    'failed_to_place_order': 'Тапсырысты ресімдеу қатесі.',
    'order_status_placed': 'Тапсырыс қабылданды',
    'order_status_collecting': 'Тапсырыс жиналуда',
    'order_status_delivery': 'Курьер жолда',
    'order_status_delivered': 'Тапсырыс жеткізілді',
    'order_status_cancelled': 'Тапсырыс тоқтатылды',
    'cancel_order_confirm_title': 'Тапсырысты тоқтату?',
    'cancel_order_confirm_msg': 'Бұл тапсырысты тоқтатуға сенімдісіз бе?',
    'support': 'Қолдау',
    'call_support': 'Қоңырау шалу',
    'chat_with_us': 'Чатқа жазу',
    'details': 'Толығырақ',
    'no_orders_yet': 'Тапсырыстар жоқ 🌸',
    'order_preview': 'Тапсырыс',
    'courier_comment_hint': 'Тапсырыс құрамы, қаптамасы және безендірілуі бойынша тілектеріңізді жазыңыз.',
    'ready': 'Дайын',
    'edit_address': 'Мекенжайды өңдеу',
    'add_new_address': 'Жаңа мекенжай қосу',
    'street_address': 'Көше және үй *',
    'street_required': 'Көшені енгізіңіз',
    'street_hint': 'мыс. Республика даңғылы, 12',
    'apt_office_floor_label': 'Пәтер / Кеңсе / Қабат',
    'apt_office_floor_example': 'мыс. 510 пәтер, 5 қабат',
    'city_label': 'Қала *',
    'city_required': 'Қаланы енгізіңіз',
    'city_hint': 'мыс. Астана',
    'set_as_default': 'Негізгі мекенжай ретінде орнату',
    'save_changes': 'Өзгерістерді сақтау',
    'error_load_profile': 'Профильді жүктеу мүмкін болмады',
    'error_sign_out': 'Шығу қатесі. Қайталап көріңіз.',
    'flowers': 'Гүлдер',
    'sweets': 'Тәттілер',
    'plants': 'Өсімдіктер',
    'bears': 'Қонжықтар',
    'balloons': 'Шарлар',
    'ai_florist_title': 'AI Флорист',
    'ai_florist_description': 'Гүлдерді таңдаңыз, бюджет пен себепті көрсетіңіз — AI тамаша букет жасады. Оны флористке жіберіңіз!',
    'generation': 'Генерация',
    'to_florist': 'Флористке',
    'create_ai_bouquet': 'AI-мен букет жасау',
    'top_pick': 'Үздік таңдау',
    'top_choice': 'Топ таңдау',
    'status_placed': 'Тапсырыс қабылданды',
    'status_collecting': 'Тапсырыс жиналуда',
    'status_delivery': 'Курьер жолда',
    'status_in_progress': 'Тапсырыс орындалуда',
    'delivery_today': 'Гүлдерді бүгін жеткіземіз',
    'searchHint': 'Гүл, дүкен іздеу...',
    'searchResults': 'Іздеу нәтижелері',
    'noResults': 'Ештеңе табылмады',
    'error_loading_product': 'Өнімді жүктеу қатесі',
    'error_loading_shop': 'Дүкенді жүктеу қатесі',
    'seed_complete': 'Сидтеу аяқталды!',
  };
}

class AppTranslations {
  final String languageCode;
  AppTranslations(this.languageCode);

  String translate(String key, [List<dynamic>? args]) {
    String value = LocalizationData.data[languageCode]?[key] ?? 
                   LocalizationData.data['en']?[key] ?? key;
    
    if (args != null && args.isNotEmpty) {
      for (int i = 0; i < args.length; i++) {
        value = value.replaceAll('{$i}', args[i].toString());
      }
    }
    return value;
  }

  String call(String key, [List<dynamic>? args]) => translate(key, args);

  // Геттеры для обратной совместимости
  String get home => this('home');
  String get search => this('search');
  String get favorites => this('favorites');
  String get cart => this('cart');
  String get profile => this('profile');
  String get myOrders => this('myOrders');
  String get savedAddresses => this('savedAddresses');
  String get language => this('language');
  String get logout => this('logout');
  String get deleteAccount => this('deleteAccount');
  String get settings => this('settings');
  String get cartEmpty => this('cartEmpty');
  String get browseFlowers => this('browseFlowers');
  String get addSomeFlowers => this('addSomeFlowers');
  String get goToCheckout => this('goToCheckout');
  String get total => this('total');
  String get delivery => this('delivery');
  String get price => this('price');
  String get clearCart => this('clearCart');
  String get removeAllItems => this('removeAllItems');
  String get commentSeller => this('commentSeller');
  String get promocode => this('promocode');
  String get usePromocode => this('usePromocode');
  String get youHavePromocode => this('youHavePromocode');
  String get orderDetails => this('orderDetails');
  String get recipient => this('recipient');
  String get address => this('address');
  String get payment => this('payment');
  String get payOrder => this('payOrder');
  String get myOrdersTitle => this('myOrdersTitle');
  String get activeOrders => this('activeOrders');
  String get historyOrders => this('historyOrders');
  String get noActiveOrders => this('noActiveOrders');
  String get repeatOrder => this('repeatOrder');
  String get orderComposition => this('orderComposition');
  String get courierComment => this('courierComment');
  String get addComment => this('addComment');
  String get savedAddressesTitle => this('savedAddressesTitle');
  String get addAddress => this('addAddress');
  String get noAddresses => this('noAddresses');
  String get defaultAddress => this('defaultAddress');
  String get street => this('street');
  String get apartment => this('apartment');
  String get city => this('city');
  String get deleteAddress => this('deleteAddress');
  String get signIn => this('signIn');
  String get signUp => this('signUp');
  String get email => this('email');
  String get password => this('password');
  String get forgotPassword => this('forgotPassword');
  String get noAccount => this('noAccount');
  String get haveAccount => this('haveAccount');
  String get save => this('save');
  String get cancel => this('cancel');
  String get delete => this('delete');
  String get edit => this('edit');
  String get retry => this('retry');
  String get yes => this('yes');
  String get no => this('no');
  String get loading => this('loading');
  String get error => this('error');
  String get success => this('success');
  String get back => this('back');
  String get selectLanguage => this('selectLanguage');
  String get notFound => this('notFound');
  String get goHome => this('goHome');
  String get searchHint => this('searchHint');
  String get searchResults => this('searchResults');
  String get noResults => this('noResults');
  String get notifications => this('notifications');
  String get about_us => this('about_us');
  String get app_name => this('app_name');
  String get about_app_description => this('about_app_description');
  String get error_load_profile => this('error_load_profile');
  String get error_sign_out => this('error_sign_out');
  String get error_load_cart => this('error_load_cart');
  String get people_add_to_order => this('people_add_to_order');
  String get postcard => this('postcard');
  String get clear => this('clear');
  String get cart_is_empty => this('cart_is_empty');
}

Future<void> setAppLanguage(String code) async {
  appLanguageNotifier.value = code;
  try {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('app_language', code);
  } catch (_) {}
}

AppTranslations get t => getTranslations();

AppTranslations getTranslations() {
  return AppTranslations(appLanguageNotifier.value);
}

mixin LanguageStateMixin<T extends StatefulWidget> on State<T> {
  @override
  void initState() {
    super.initState();
    appLanguageNotifier.addListener(_onLangChanged);
  }

  @override
  void dispose() {
    appLanguageNotifier.removeListener(_onLangChanged);
    super.dispose();
  }

  void _onLangChanged() {
    if (mounted) setState(() {});
  }
}
