// Mocks generated by Mockito 5.4.6 from annotations
// in flowery_app/test/services/ai__florist_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flowery_app/models/api/api_order.dart' as _i3;
import 'package:flowery_app/models/api/api_responses.dart' as _i2;
import 'package:flowery_app/services/api/api_client.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRecommendationResponse_0 extends _i1.SmartFake
    implements _i2.RecommendationResponse {
  _FakeRecommendationResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeImageGenerationResponse_1 extends _i1.SmartFake
    implements _i2.ImageGenerationResponse {
  _FakeImageGenerationResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeThreeDStructureResponse_2 extends _i1.SmartFake
    implements _i2.ThreeDStructureResponse {
  _FakeThreeDStructureResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiOrder_3 extends _i1.SmartFake implements _i3.ApiOrder {
  _FakeApiOrder_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCatalogFlowersResponse_4 extends _i1.SmartFake
    implements _i2.CatalogFlowersResponse {
  _FakeCatalogFlowersResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeComposeBouquetResponse_5 extends _i1.SmartFake
    implements _i2.ComposeBouquetResponse {
  _FakeComposeBouquetResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i4.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.RecommendationResponse> recommendFromText(
          Map<String, dynamic>? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #recommendFromText,
          [body],
        ),
        returnValue: _i5.Future<_i2.RecommendationResponse>.value(
            _FakeRecommendationResponse_0(
          this,
          Invocation.method(
            #recommendFromText,
            [body],
          ),
        )),
      ) as _i5.Future<_i2.RecommendationResponse>);

  @override
  _i5.Future<_i2.ImageGenerationResponse> generateImage(
          Map<String, dynamic>? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateImage,
          [body],
        ),
        returnValue: _i5.Future<_i2.ImageGenerationResponse>.value(
            _FakeImageGenerationResponse_1(
          this,
          Invocation.method(
            #generateImage,
            [body],
          ),
        )),
      ) as _i5.Future<_i2.ImageGenerationResponse>);

  @override
  _i5.Future<_i2.ThreeDStructureResponse> get3DStructure(
          Map<String, dynamic>? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #get3DStructure,
          [body],
        ),
        returnValue: _i5.Future<_i2.ThreeDStructureResponse>.value(
            _FakeThreeDStructureResponse_2(
          this,
          Invocation.method(
            #get3DStructure,
            [body],
          ),
        )),
      ) as _i5.Future<_i2.ThreeDStructureResponse>);

  @override
  _i5.Future<_i3.ApiOrder> createOrder(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrder,
          [body],
        ),
        returnValue: _i5.Future<_i3.ApiOrder>.value(_FakeApiOrder_3(
          this,
          Invocation.method(
            #createOrder,
            [body],
          ),
        )),
      ) as _i5.Future<_i3.ApiOrder>);

  @override
  _i5.Future<_i3.ApiOrder> getOrder(String? orderId) => (super.noSuchMethod(
        Invocation.method(
          #getOrder,
          [orderId],
        ),
        returnValue: _i5.Future<_i3.ApiOrder>.value(_FakeApiOrder_3(
          this,
          Invocation.method(
            #getOrder,
            [orderId],
          ),
        )),
      ) as _i5.Future<_i3.ApiOrder>);

  @override
  _i5.Future<_i3.ApiOrder> reviewOrder(
    String? orderId,
    Map<String, String>? body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reviewOrder,
          [
            orderId,
            body,
          ],
        ),
        returnValue: _i5.Future<_i3.ApiOrder>.value(_FakeApiOrder_3(
          this,
          Invocation.method(
            #reviewOrder,
            [
              orderId,
              body,
            ],
          ),
        )),
      ) as _i5.Future<_i3.ApiOrder>);

  @override
  _i5.Future<_i3.ApiOrder> markOrderAsPaid(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markOrderAsPaid,
          [orderId],
        ),
        returnValue: _i5.Future<_i3.ApiOrder>.value(_FakeApiOrder_3(
          this,
          Invocation.method(
            #markOrderAsPaid,
            [orderId],
          ),
        )),
      ) as _i5.Future<_i3.ApiOrder>);

  @override
  _i5.Future<void> checkHealth() => (super.noSuchMethod(
        Invocation.method(
          #checkHealth,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.CatalogFlowersResponse> getCatalogFlowers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCatalogFlowers,
          [],
        ),
        returnValue: _i5.Future<_i2.CatalogFlowersResponse>.value(
            _FakeCatalogFlowersResponse_4(
          this,
          Invocation.method(
            #getCatalogFlowers,
            [],
          ),
        )),
      ) as _i5.Future<_i2.CatalogFlowersResponse>);

  @override
  _i5.Future<_i2.ComposeBouquetResponse> composeBouquet(
          Map<String, dynamic>? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #composeBouquet,
          [body],
        ),
        returnValue: _i5.Future<_i2.ComposeBouquetResponse>.value(
            _FakeComposeBouquetResponse_5(
          this,
          Invocation.method(
            #composeBouquet,
            [body],
          ),
        )),
      ) as _i5.Future<_i2.ComposeBouquetResponse>);
}
