// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnZI1dg5ccvFiKvwin91s0_evx0tRPkxE',
    appId: '1:771903129521:android:d9f2396e327e797f959f90',
    messagingSenderId: '771903129521',
    projectId: 'flowercy-26a77',
    storageBucket: 'flowercy-26a77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKUQS_Exf2de1MfpHd9n0X5D5hXMU665g',
    appId: '1:771903129521:ios:3cb1da95feeee513959f90',
    messagingSenderId: '771903129521',
    projectId: 'flowercy-26a77',
    storageBucket: 'flowercy-26a77.firebasestorage.app',
    iosBundleId: 'com.example.floweryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKUQS_Exf2de1MfpHd9n0X5D5hXMU665g',
    appId: '1:771903129521:ios:3cb1da95feeee513959f90',
    messagingSenderId: '771903129521',
    projectId: 'flowercy-26a77',
    storageBucket: 'flowercy-26a77.firebasestorage.app',
    iosBundleId: 'com.example.floweryApp',
  );
}
